# GitHub Labels Configuration

# Type Labels
- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"

- name: 'feature'
  color: 'a2eeef'
  description: 'New feature or request'

- name: 'enhancement'
  color: 'a2eeef'
  description: 'Improvement to existing functionality'

- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'refactor'
  color: 'fbca04'
  description: 'Code refactoring without functional changes'

- name: 'performance'
  color: 'ff6b6b'
  description: 'Performance improvements'

- name: 'security'
  color: 'ee0701'
  description: 'Security-related issues or improvements'

- name: 'test'
  color: '1d76db'
  description: 'Testing-related changes'

# Priority Labels
- name: 'priority: critical'
  color: 'b60205'
  description: 'Critical priority - needs immediate attention'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority'

- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority'

# Status Labels
- name: 'status: blocked'
  color: 'd93f0b'
  description: 'Blocked by another issue or external dependency'

- name: 'status: in progress'
  color: '0052cc'
  description: 'Currently being worked on'

- name: 'status: review needed'
  color: 'fbca04'
  description: 'Awaiting review'

- name: 'status: ready'
  color: '0e8a16'
  description: 'Ready to be worked on'

# Workflow Labels
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'

- name: 'question'
  color: 'd876e3'
  description: 'Further information is requested'

- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or pull request already exists'

- name: 'invalid'
  color: 'e4e669'
  description: "This doesn't seem right"

# Category Labels
- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates'

- name: 'github-actions'
  color: '000000'
  description: 'GitHub Actions workflows'

- name: 'automated'
  color: 'ededed'
  description: 'Automated changes (bots, CI/CD)'

- name: 'breaking change'
  color: 'd73a4a'
  description: 'Breaking API or behavior change'

- name: 'ci/cd'
  color: '0052cc'
  description: 'CI/CD pipeline related'

# Size Labels
- name: 'size: xs'
  color: 'c2e0c6'
  description: 'Extra small change'

- name: 'size: s'
  color: 'b4d5b8'
  description: 'Small change'

- name: 'size: m'
  color: 'a2cba7'
  description: 'Medium change'

- name: 'size: l'
  color: '8fc193'
  description: 'Large change'

- name: 'size: xl'
  color: '7cb77f'
  description: 'Extra large change'
